export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SINGUP_REQUESTED = "SINGUP_REQUESTED";
export const SINGUP_SUCCEEDED = "SINGUP_SUCCEEDED";
export const SINGUP_FAILED = "SINGUP_FAILED";